Repository We-a-vers/UTA, pull requests merged in 2023-05, with the labels that each got.

#9 Update index.html
  index.html
  source/protected.html
Labels: fixes

#14 Update index.html
  index.html
Labels: coding task

#41 Review & revise all ADR's except Website Hosting
  specs/adr/05042023-FileOrganization.md
  specs/adr/05042023-FirebaseUsage.md
  specs/adr/05042023-Merging.md
  specs/adr/05042023-NamingConventions.md
Labels: non-coding task

#42 Create codacy.yml
  .github/workflows/codacy.yml
Labels: non-coding task

#30 David-archive-lofi
  source/archive/archive.css
  source/archive/archive.html
  source/archive/archive.js
  source/archive/example.txt
  source/archive/placeholder_image.png
  source/archive/placeholder_image2.png
Labels: coding task

#48 events lofi updated
  source/events/events.css
  source/events/events.html
  source/events/example.txt
Labels: coding task

#52 Benjamin-about-us-lofi
  source/about-us/about-us.css
  source/about-us/about-us.html
Labels: coding task

#49 Update home page lo-fi
  index.html
  source/Home/home.css
Labels: coding task
